/**
 * Drives all 9 core flows from docs/FRONTEND_FLOWS.md end-to-end against a
 * locally running app (`pnpm start:dev`) + Stellar testnet, using the wallets
 * generated by setup-wallets.ts.
 *
 * Two campaigns:
 *  - Campaign A: fully funded by investor1+investor2 (600/400 of a 1000 goal),
 *    exercises invest -> dividend deposit/claim -> two sequential milestone
 *    releases (Flows 3-8).
 *  - Campaign B: partially funded by investor1 (200 of a 500 goal), then
 *    admin-cancelled to exercise the refund path (Flow 9).
 *
 * Run: npx tsx scripts/e2e/full-flow.ts   (after setup-wallets.ts)
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { config as loadEnv } from 'dotenv';
import { Keypair, TransactionBuilder } from '@stellar/stellar-base';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../../generated/prisma/client';

const ROOT = join(__dirname, '..', '..');
loadEnv({ path: join(ROOT, '.env') });

const BASE_URL = `http://localhost:${process.env.PORT ?? 3000}`;
const NETWORK_PASSPHRASE = process.env.STELLAR_NETWORK_PASSPHRASE!;
/** Name of the httpOnly cookie AuthController sets the JWT under (auth-cookie.constants.ts). */
const AUTH_COOKIE_NAME = 'creon_access_token';

// Minimal valid 1x1 transparent PNG, reused as the KYC id/selfie + milestone proof stand-in.
const TINY_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
);

interface Wallet {
  role: 'admin' | 'entrepreneur' | 'investor1' | 'investor2';
  publicKey: string;
  secretKey: string;
}

const wallets: Wallet[] = JSON.parse(
  readFileSync(join(__dirname, 'wallets.local.json'), 'utf8'),
);
function wallet(role: Wallet['role']): Wallet {
  const w = wallets.find((x) => x.role === role);
  if (!w) throw new Error(`wallet not found for role ${role}; run setup-wallets.ts first`);
  return w;
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
});

// ---------- generic helpers ----------

async function apiRequest(
  method: string,
  path: string,
  opts: { token?: string; body?: unknown; form?: FormData } = {},
): Promise<any> {
  const headers: Record<string, string> = {};
  if (opts.token) headers['Authorization'] = `Bearer ${opts.token}`;
  let body: BodyInit | undefined;
  if (opts.form) {
    body = opts.form;
  } else if (opts.body !== undefined) {
    headers['Content-Type'] = 'application/json';
    body = JSON.stringify(opts.body);
  }
  const res = await fetch(`${BASE_URL}${path}`, { method, headers, body });
  const text = await res.text();
  let json: any;
  try {
    json = text ? JSON.parse(text) : undefined;
  } catch {
    json = text;
  }
  if (!res.ok) {
    throw new Error(`${method} ${path} -> ${res.status}: ${JSON.stringify(json)}`);
  }
  // Every response is enveloped as { statusCode, message, data } — see CLAUDE.md's
  // "Every HTTP response is enveloped" convention.
  return json?.data;
}

/** The JWT is delivered only as an httpOnly Set-Cookie (AuthController.setAuthCookie),
 *  not in the response body — extract it directly and reuse it as a Bearer token, since
 *  JwtAuthGuard accepts either. */
async function authRequest(path: '/auth/login' | '/auth/register', body: unknown): Promise<string> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`POST ${path} -> ${res.status}: ${await res.text()}`);
  }
  const setCookies = res.headers.getSetCookie();
  const authCookie = setCookies
    .map((c) => c.split(';')[0])
    .find((c) => c.startsWith(`${AUTH_COOKIE_NAME}=`));
  if (!authCookie) {
    throw new Error(`No ${AUTH_COOKIE_NAME} cookie in ${path} response`);
  }
  return decodeURIComponent(authCookie.slice(AUTH_COOKIE_NAME.length + 1));
}

function randomNik(): string {
  return Array.from({ length: 16 }, () => Math.floor(Math.random() * 10)).join('');
}

function signChallenge(kp: Keypair, message: string): string {
  return kp.sign(Buffer.from(message)).toString('base64');
}

function signXdr(kp: Keypair, xdr: string): string {
  const tx = TransactionBuilder.fromXDR(xdr, NETWORK_PASSPHRASE);
  tx.sign(kp);
  return tx.toXDR();
}

async function pollUntil<T>(
  label: string,
  fn: () => Promise<T>,
  predicate: (v: T) => boolean,
  opts: { intervalMs?: number; timeoutMs?: number } = {},
): Promise<T> {
  const interval = opts.intervalMs ?? 5000;
  const timeout = opts.timeoutMs ?? 90000;
  const start = Date.now();
  for (;;) {
    const v = await fn();
    if (predicate(v)) {
      console.log(`  ✓ ${label} = ${JSON.stringify(v)}`);
      return v;
    }
    if (Date.now() - start > timeout) {
      throw new Error(`Timeout waiting for ${label} (last value: ${JSON.stringify(v)})`);
    }
    await new Promise((r) => setTimeout(r, interval));
  }
}

// ---------- auth ----------

async function challengeMessage(publicKey: string): Promise<string> {
  const res = await apiRequest('POST', '/auth/challenge', {
    body: { walletAddress: publicKey },
  });
  return res.message;
}

async function loginWallet(w: Wallet): Promise<string> {
  const kp = Keypair.fromSecret(w.secretKey);
  const message = await challengeMessage(w.publicKey);
  const signature = signChallenge(kp, message);
  return authRequest('/auth/login', { walletAddress: w.publicKey, signature });
}

async function registerOrLogin(
  w: Wallet,
  role: 'ENTREPRENEUR' | 'INVESTOR',
  email?: string,
): Promise<string> {
  const kp = Keypair.fromSecret(w.secretKey);
  const message = await challengeMessage(w.publicKey);
  const signature = signChallenge(kp, message);
  try {
    return await authRequest('/auth/register', { walletAddress: w.publicKey, signature, role, email });
  } catch (err) {
    if (String(err).includes('409')) {
      console.log(`  [${role}] already registered, logging in instead`);
      return loginWallet(w);
    }
    throw err;
  }
}

async function ensureAdmin(w: Wallet): Promise<string> {
  const byWallet = await prisma.user.findUnique({ where: { walletAddress: w.publicKey } });
  if (!byWallet || !byWallet.roles.includes('ADMIN' as any)) {
    const seededAdmin = await prisma.user.findFirst({ where: { roles: { has: 'ADMIN' as any } } });
    if (seededAdmin) {
      await prisma.user.update({
        where: { id: seededAdmin.id },
        data: { walletAddress: w.publicKey },
      });
      console.log('  granted ADMIN role to generated wallet (via seeded admin row)');
    } else {
      await prisma.user.create({ data: { walletAddress: w.publicKey, roles: ['ADMIN' as any] } });
      console.log('  created a fresh ADMIN user for the generated wallet');
    }
  }
  return loginWallet(w);
}

// ---------- KYC ----------

async function submitKyc(token: string, fullName: string): Promise<void> {
  const form = new FormData();
  form.append('fullName', fullName);
  form.append('nationalId', randomNik());
  form.append('idCard', new Blob([TINY_PNG], { type: 'image/png' }), 'idcard.png');
  form.append('selfie', new Blob([TINY_PNG], { type: 'image/png' }), 'selfie.png');
  await apiRequest('POST', '/kyc', { token, form });
}

async function ensureKycApproved(
  token: string,
  adminToken: string,
  userId: string,
  fullName: string,
): Promise<void> {
  const me = await apiRequest('GET', '/kyc/me', { token }).catch(() => null);
  if (me?.status === 'APPROVED') {
    console.log(`  [${fullName}] KYC already APPROVED, skipping`);
    return;
  }
  if (me?.status !== 'PENDING') {
    await submitKyc(token, fullName);
  }
  await apiRequest('POST', `/admin/kyc/${userId}/approve`, { token: adminToken });
}

async function whitelistStatus(userId: string): Promise<string | undefined> {
  const profile = await prisma.kycProfile.findUnique({ where: { userId } });
  return profile?.whitelistStatus;
}

// ---------- proposals / campaigns ----------

interface MilestoneInput {
  order: number;
  title: string;
  description: string;
  amount: string;
}

async function createAndApproveCampaign(
  entToken: string,
  adminToken: string,
  input: {
    businessName: string;
    requestedAmount: string;
    milestones: MilestoneInput[];
  },
): Promise<string> {
  const proposal = await apiRequest('POST', '/proposals', {
    token: entToken,
    body: {
      businessName: input.businessName,
      businessDescription: `${input.businessName} - e2e test proposal`,
      category: 'F&B',
      location: 'Jakarta',
      requestedAmount: input.requestedAmount,
      lockPeriodDays: 30,
      milestones: input.milestones,
    },
  });
  await apiRequest('POST', `/proposals/${proposal.id}/submit`, { token: entToken });
  await apiRequest('POST', `/admin/proposals/${proposal.id}/approve`, { token: adminToken });

  const campaign = await pollUntil(
    `Campaign row for proposal ${proposal.id}`,
    () => prisma.campaign.findUnique({ where: { proposalId: proposal.id } }),
    (c) => c !== null,
    { intervalMs: 1000, timeoutMs: 15000 },
  );
  await pollUntil(
    `${input.businessName} deployStatus LIVE`,
    async () => (await prisma.campaign.findUnique({ where: { id: campaign!.id } }))!.deployStatus,
    (s) => s === 'LIVE',
    { intervalMs: 5000, timeoutMs: 180000 },
  );
  return campaign!.id;
}

async function invest(token: string, campaignId: string, amount: string, kp: Keypair): Promise<void> {
  const prepared = await apiRequest('POST', `/campaigns/${campaignId}/investments/prepare`, {
    token,
    body: { amount },
  });
  const signedXdr = signXdr(kp, prepared.xdr);
  await apiRequest('POST', `/campaigns/${campaignId}/investments`, {
    token,
    body: { signedXdr },
  });
}

// ---------- main ----------

interface FlowResult {
  flow: string;
  ok: boolean;
  detail?: string;
}
const results: FlowResult[] = [];
function record(flow: string, ok: boolean, detail?: string) {
  results.push({ flow, ok, detail });
  console.log(`${ok ? '✅' : '❌'} ${flow}${detail ? ': ' + detail : ''}`);
}

async function main() {
  const adminW = wallet('admin');
  const entW = wallet('entrepreneur');
  const inv1W = wallet('investor1');
  const inv2W = wallet('investor2');
  const entKp = Keypair.fromSecret(entW.secretKey);
  const inv1Kp = Keypair.fromSecret(inv1W.secretKey);
  const inv2Kp = Keypair.fromSecret(inv2W.secretKey);

  // ---- Flow 1: auth ----
  console.log('\n=== Flow 1: Register / Login ===');
  const entToken = await registerOrLogin(entW, 'ENTREPRENEUR', 'entrepreneur@creon.e2e.test');
  const inv1Token = await registerOrLogin(inv1W, 'INVESTOR');
  const inv2Token = await registerOrLogin(inv2W, 'INVESTOR');
  const adminToken = await ensureAdmin(adminW);
  record('Flow 1 — Register/Login (entrepreneur, 2 investors, admin)', true);

  // ---- Flow 2: KYC + whitelist ----
  console.log('\n=== Flow 2: KYC Submission & Approval ===');
  const entUser = await prisma.user.findUniqueOrThrow({ where: { walletAddress: entW.publicKey } });
  const inv1User = await prisma.user.findUniqueOrThrow({ where: { walletAddress: inv1W.publicKey } });
  const inv2User = await prisma.user.findUniqueOrThrow({ where: { walletAddress: inv2W.publicKey } });
  await ensureKycApproved(entToken, adminToken, entUser.id, 'Entrepreneur E2E');
  await ensureKycApproved(inv1Token, adminToken, inv1User.id, 'Investor One E2E');
  await ensureKycApproved(inv2Token, adminToken, inv2User.id, 'Investor Two E2E');
  await pollUntil('investor1 whitelistStatus', () => whitelistStatus(inv1User.id), (s) => s === 'WHITELISTED', {
    timeoutMs: 60000,
  });
  await pollUntil('investor2 whitelistStatus', () => whitelistStatus(inv2User.id), (s) => s === 'WHITELISTED', {
    timeoutMs: 60000,
  });
  record('Flow 2 — KYC approval + on-chain whitelist sync', true);

  // ---- Flow 3+4: Campaign A ----
  // RESUME_CAMPAIGN_A_ID lets a prior successful Campaign A (already deployed +
  // invested on-chain) be reused instead of re-deploying and re-investing —
  // useful when only later flows (dividend/milestones) need re-running.
  const resumeCampaignAId = process.env.RESUME_CAMPAIGN_A_ID;
  let campaignAId: string;
  if (resumeCampaignAId) {
    console.log(`\n=== Flow 3+4+5: Resuming existing Campaign A ${resumeCampaignAId} ===`);
    campaignAId = resumeCampaignAId;
    record('Flow 3+4 — Reused existing Campaign A (resume)', true, campaignAId);
    record('Flow 5 — Reused existing investments (resume)', true);
  } else {
    console.log('\n=== Flow 3+4: Proposal + Auto-Deploy (Campaign A) ===');
    campaignAId = await createAndApproveCampaign(entToken, adminToken, {
      businessName: 'Warung E2E Nusantara',
      requestedAmount: '1000.0000000',
      milestones: [
        { order: 1, title: 'Renovate stall', description: 'Phase 1 build-out', amount: '600.0000000' },
        { order: 2, title: 'Buy equipment', description: 'Phase 2 equipment', amount: '400.0000000' },
      ],
    });
    record('Flow 3+4 — Proposal submit/approve + campaign auto-deploy (A)', true, campaignAId);

    // ---- Flow 5: invest ----
    console.log('\n=== Flow 5: Invest (Campaign A) ===');
    await invest(inv1Token, campaignAId, '600.0000000', inv1Kp);
    await invest(inv2Token, campaignAId, '400.0000000', inv2Kp);
    record('Flow 5 — Investor1 (600) + Investor2 (400) invest', true);
  }
  await pollUntil(
    'TokenHolding count for Campaign A',
    () => prisma.tokenHolding.count({ where: { campaignId: campaignAId, holderId: { not: null } } }),
    (c) => c >= 2,
    { intervalMs: 10000, timeoutMs: 120000 },
  );

  // ---- Flow 6+7: dividend ----
  console.log('\n=== Flow 6+7: Deposit Profit + Claim Dividend ===');
  const depositPrepared = await apiRequest(
    'POST',
    `/campaigns/${campaignAId}/distributions/deposit/prepare`,
    { token: entToken, body: { amount: '100.0000000' } },
  );
  const depositSignedXdr = signXdr(entKp, depositPrepared.xdr);
  const distribution = await apiRequest(
    'POST',
    `/campaigns/${campaignAId}/distributions/deposit`,
    { token: entToken, body: { signedXdr: depositSignedXdr } },
  );
  await pollUntil(
    'ProfitDistribution status',
    async () => (await prisma.profitDistribution.findUnique({ where: { id: distribution.id } }))!.status,
    (s) => s === 'COMPLETED',
    { timeoutMs: 90000 },
  );
  for (const [label, token, kp] of [
    ['investor1', inv1Token, inv1Kp],
    ['investor2', inv2Token, inv2Kp],
  ] as const) {
    const claimPrepared = await apiRequest(
      'POST',
      `/distributions/${distribution.id}/claim/prepare`,
      { token },
    );
    const claimSignedXdr = signXdr(kp, claimPrepared.xdr);
    await apiRequest('POST', `/distributions/${distribution.id}/claim`, {
      token,
      body: { signedXdr: claimSignedXdr },
    });
    console.log(`  ${label} claimed dividend`);
  }
  record('Flow 6+7 — Deposit 100 USDC profit + both investors claim', true);

  // ---- Flow 8: milestones ----
  console.log('\n=== Flow 8: Milestone Submission & Voting ===');
  const milestones = await prisma.milestone.findMany({
    where: { campaignId: campaignAId },
    orderBy: { order: 'asc' },
  });
  for (const m of milestones) {
    const form = new FormData();
    form.append('proof', new Blob([TINY_PNG], { type: 'image/png' }), 'proof.png');
    await apiRequest('POST', `/milestones/${m.id}/submit`, { token: entToken, form });
    await apiRequest('POST', `/milestones/${m.id}/vote`, {
      token: inv1Token,
      body: { choice: 'APPROVE' },
    });
    await apiRequest('POST', `/milestones/${m.id}/vote`, {
      token: inv2Token,
      body: { choice: 'APPROVE' },
    });
    await pollUntil(
      `Milestone ${m.order} status`,
      async () => (await prisma.milestone.findUnique({ where: { id: m.id } }))!.status,
      (s) => s === 'RELEASED',
      { intervalMs: 10000, timeoutMs: 180000 },
    );
  }
  record(`Flow 8 — ${milestones.length} sequential milestone releases (voted APPROVE)`, true);

  // ---- Campaign B setup ----
  console.log('\n=== Flow 3+4+5 again: Campaign B (for refund test) ===');
  const campaignBId = await createAndApproveCampaign(entToken, adminToken, {
    businessName: 'Toko E2E Cancel-Test',
    requestedAmount: '500.0000000',
    milestones: [
      { order: 1, title: 'Single milestone', description: 'Not released — campaign will be cancelled', amount: '500.0000000' },
    ],
  });
  await invest(inv1Token, campaignBId, '200.0000000', inv1Kp);
  record('Flow 3+4+5 — Campaign B live + investor1 invests 200', true, campaignBId);

  // ---- Flow 9: cancel + refund ----
  console.log('\n=== Flow 9: Admin Cancel + Investor Refund Claim ===');
  await apiRequest('POST', `/admin/campaigns/${campaignBId}/cancel`, {
    token: adminToken,
    body: { reason: 'e2e test: simulated fraud/failure cancellation' },
  });
  await pollUntil(
    'Refund status',
    async () => (await prisma.refund.findUnique({ where: { campaignId: campaignBId } }))?.status,
    (s) => s === 'COMPLETED',
    { intervalMs: 10000, timeoutMs: 120000 },
  );
  const refund = await prisma.refund.findUniqueOrThrow({ where: { campaignId: campaignBId } });
  const refundPrepared = await apiRequest('POST', `/refunds/${refund.id}/claim/prepare`, {
    token: inv1Token,
  });
  const refundSignedXdr = signXdr(inv1Kp, refundPrepared.xdr);
  await apiRequest('POST', `/refunds/${refund.id}/claim`, {
    token: inv1Token,
    body: { signedXdr: refundSignedXdr },
  });
  record('Flow 9 — Admin cancel Campaign B + investor1 refund claim', true);
}

main()
  .catch((err) => {
    console.error('\n❌ Fatal error:', err);
    record('ABORTED', false, String(err?.message ?? err));
  })
  .finally(async () => {
    console.log('\n========== SUMMARY ==========');
    for (const r of results) {
      console.log(`${r.ok ? '✅' : '❌'} ${r.flow}${r.detail ? ' — ' + r.detail : ''}`);
    }
    await prisma.$disconnect();
    process.exit(results.every((r) => r.ok) ? 0 : 1);
  });
